spring:
  application:
    name: demo

  datasource:
    url: jdbc:h2:mem:currencydb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 50

  h2:
    console:
      enabled: true

currency:
  api:
    key: 21ba585b7ad8ad6e152dfd57
    base-url: https://v6.exchangerate-api.com/v6

resilience4j:
  retry:
    instances:
      exchangeClient:
        max-attempts: 3
        wait-duration: 1s

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
